name: v2a_eval
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip=24.0
  - ffmpeg<7
  - git 
  - make
  - cmake
  - gxx_linux-64    # C++ compiler (Linux) - remove if on Windows/Mac
  - gcc_linux-64    # C compiler (Linux) - remove if on Windows/Mac
  - libsndfile
  - cuda-nvcc=12.1
  - cuda-version=12.1

  - pytorch=2.4.1
  - torchvision=0.19.1
  - torchaudio=2.4.1
  - pytorch-cuda=12.1

  - pip:
    - git+https://github.com/pytorch/fairseq.git@v0.12.2
    - cdpam==0.0.6
    - wavencoder==0.1.2
    - numpy==1.26.1
    - pandas==2.0.2
    - scipy==1.15.3
    - matplotlib==3.8.0
    - scikit-learn==1.0.2
    - scikit-image==0.19.3
    - seaborn==0.13.2
    - tqdm==4.66.1
    - pyyaml==6.0.1
    - ipython==8.16.1
    - jupyterlab
    - fvcore==0.1.5.post20221221
    - submitit==1.5.3
    - iopath==0.1.10
    - librosa==0.9.2
    - soundfile==0.11.0
    - resampy==0.2.2
    - termcolor==2.1.0
    - auraloss==0.4.0
    - descript-audio-codec==1.0.0
    - encodec==0.1.1
    - pedalboard==0.7.4
    - prefigure
    - PyWavelets==1.6.0
    - pytorch-lightning==2.5.6
    - pyloudnorm==0.1.1
    - julius==0.2.7
    - pandarallel==1.6.5
    - torchlibrosa==0.1.0
    - torchopenl3==1.0.1
    - nnAudio==0.3.3
    - hear21passt==0.0.26
    - laion-clap==1.1.7
    - mutagen==1.47.0
    - GitPython==3.1.40
    - boto3==1.34.60
    - transformers==4.57.1
    - diffusers==0.35.2
    - accelerate
    - einops==0.8.1
    - einops-exts==0.0.4
    - ema-pytorch==0.2.3
    - pytorch-lightning==2.5.6
    - torchmetrics==0.11.4
    - wandb==0.15.4
    - hydra-core==1.0.7
    - pytest==7.4.3
    - hydra-colorlog==1.2.0
    - pylint==3.0.2
    - omegaconf==2.0.6
    - webdataset==0.2.48
    - timm==1.0.22
    - safetensors==0.7.0
    - gradio==6.0.0
    - importlib-resources
    - huggingface-hub==0.36.0
    - sentencepiece==0.1.99
    - openpyxl==3.1.2
    - s3fs==2025.10.0
    - moviepy==1.0.3
    - annoy==1.17.3
    - imageio-ffmpeg==0.6.0
    - facenet-pytorch==2.5.2
    - kornia==0.8.2
    - alias-free-torch==0.0.6
    - x-transformers==2.11.23
    - python-dotenv
    - mauve-text==0.4.0
    - tensordict==0.10.0
    - rich==13.7.1
    - mpi4py==4.1.1
    - gdown==5.2.0
    - dictdiffer==0.9.0
    - networkx==2.6.3
    - yt-dlp
    - soxr==1.0.0
    - ninja==1.11.1.1
    - git+https://github.com/hkchengrex/ImageBind.git
    - opencv-python-headless==4.9.0.80